import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { test } from "node:test";

import {
  cargoBuildCommand,
  cargoClippyCommand,
  importedMemory,
  lockedVersion,
  NIGHTLY_TOOLCHAIN,
  parseWasmBindgenVersion,
  THREADS_RUSTFLAGS,
  VARIANTS,
  wasmBindgenArgs,
} from "../../scripts/build-wasm.mjs";

const repoRoot = process.cwd();
const readRepoFile = (...parts) => fs.readFileSync(path.join(repoRoot, ...parts), "utf8");

// --- Tiny wasm binaries ---

function leb128(value) {
  const bytes = [];
  let rest = value;
  do {
    let byte = rest & 0x7f;
    rest >>>= 7;
    if (rest !== 0) {
      byte |= 0x80;
    }
    bytes.push(byte);
  } while (rest !== 0);
  return bytes;
}

const name = (text) => [...leb128(text.length), ...Buffer.from(text, "utf8")];
const section = (id, payload) => [id, ...leb128(payload.length), ...payload];
const vector = (items) => [...leb128(items.length), ...items.flat()];

const funcImport = [...name("env"), ...name("f"), 0x00, ...leb128(0)];
const memoryImport = (limits) => [...name("env"), ...name("memory"), 0x02, ...limits];
// One `() -> ()` function type, so the function import is valid.
const typeSection = section(1, vector([[0x60, 0x00, 0x00]]));
const customSection = section(0, [...name("producers"), 0x01, 0x02]);

function wasm(...imports) {
  return Uint8Array.from([
    ...[0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00],
    ...customSection,
    ...typeSection,
    ...section(2, vector(imports)),
  ]);
}

test("importedMemory reads a shared memory import with a maximum", () => {
  const bytes = wasm(funcImport, memoryImport([0x03, ...leb128(17), ...leb128(16384)]));

  assert.deepEqual(importedMemory(bytes), { shared: true, minimum: 17, maximum: 16384 });
});

test("importedMemory reads a non-shared memory import", () => {
  assert.deepEqual(importedMemory(wasm(memoryImport([0x01, ...leb128(1), ...leb128(2)]))), {
    shared: false,
    minimum: 1,
    maximum: 2,
  });
  assert.deepEqual(importedMemory(wasm(funcImport, memoryImport([0x00, ...leb128(300)]))), {
    shared: false,
    minimum: 300,
    maximum: null,
  });
});

test("importedMemory returns null without a memory import", () => {
  assert.equal(importedMemory(wasm(funcImport)), null);
  assert.equal(
    importedMemory(Uint8Array.from([0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00])),
    null,
  );
});

test("importedMemory rejects bytes that are not a wasm module", () => {
  assert.throws(() => importedMemory(Uint8Array.from([0x7f, 0x45, 0x4c, 0x46])), /not a wasm/);
  assert.throws(() => importedMemory(wasm(funcImport).slice(0, -2)), /truncated/);
});

// --- Versions ---

const CARGO_LOCK = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "wasm-bindgen-macro"
version = "0.2.200"

[[package]]
name = "wasm-bindgen"
version = "0.2.129"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;

test("lockedVersion reads one package's version from Cargo.lock", () => {
  assert.equal(lockedVersion(CARGO_LOCK, "wasm-bindgen"), "0.2.129");
  assert.equal(lockedVersion(CARGO_LOCK, "wasm-bindgen-macro"), "0.2.200");
  assert.throws(() => lockedVersion(CARGO_LOCK, "js-sys"), /Cargo\.lock has no js-sys package/);
});

test("lockedVersion reads the repository's wasm-bindgen", () => {
  assert.match(lockedVersion(readRepoFile("Cargo.lock"), "wasm-bindgen"), /^\d+\.\d+\.\d+$/);
});

test("parseWasmBindgenVersion reads the CLI's --version output", () => {
  assert.equal(parseWasmBindgenVersion("wasm-bindgen 0.2.129\n"), "0.2.129");
  assert.equal(parseWasmBindgenVersion("something else"), null);
});

// --- Build commands ---

test("the threaded build uses exactly the W0 RUSTFLAGS", () => {
  assert.deepEqual(THREADS_RUSTFLAGS, [
    "-C",
    "target-feature=+atomics,+bulk-memory",
    "-C",
    "link-arg=--shared-memory",
    "-C",
    "link-arg=--max-memory=1073741824",
    "-C",
    "link-arg=--import-memory",
    "-C",
    "link-arg=--export=__wasm_init_tls",
    "-C",
    "link-arg=--export=__tls_size",
    "-C",
    "link-arg=--export=__tls_align",
    "-C",
    "link-arg=--export=__tls_base",
  ]);
});

test("the single-threaded build uses the pinned stable toolchain", () => {
  const { command, args, env } = cargoBuildCommand(VARIANTS.single);

  assert.equal(command, "cargo");
  assert.deepEqual(args, [
    "build",
    "-p",
    "primeval-wasm",
    "--profile",
    "wasm-release",
    "--target",
    "wasm32-unknown-unknown",
    "--target-dir",
    "target",
  ]);
  assert.deepEqual(env, {});
  assert.equal(
    VARIANTS.single.wasm,
    path.join("target", "wasm32-unknown-unknown", "wasm-release", "primeval_wasm.wasm"),
  );
  assert.equal(VARIANTS.single.outDir, path.join("wasm", "single"));
  assert.equal(VARIANTS.single.shared, false);
});

test("the threaded build uses the nightly, build-std and its own target dir", () => {
  const { command, args, env } = cargoBuildCommand(VARIANTS.threaded);

  assert.equal(command, "cargo");
  assert.deepEqual(args, [
    `+${NIGHTLY_TOOLCHAIN}`,
    "build",
    "-p",
    "primeval-wasm",
    "--profile",
    "wasm-release",
    "--target",
    "wasm32-unknown-unknown",
    "--target-dir",
    path.join("target", "wasm-threads"),
    "--features",
    "threads",
    "-Z",
    "build-std=panic_abort,std",
  ]);
  assert.deepEqual(env, { RUSTFLAGS: THREADS_RUSTFLAGS.join(" ") });
  assert.equal(
    VARIANTS.threaded.wasm,
    path.join(
      "target",
      "wasm-threads",
      "wasm32-unknown-unknown",
      "wasm-release",
      "primeval_wasm.wasm",
    ),
  );
  assert.equal(VARIANTS.threaded.outDir, path.join("wasm", "threaded"));
  assert.equal(VARIANTS.threaded.shared, true);
});

test("clippy checks the single-threaded variant on the pinned stable toolchain", () => {
  const command = cargoClippyCommand();
  assert.deepEqual(command.args, [
    "clippy",
    "-p",
    "primeval-wasm",
    "--target",
    "wasm32-unknown-unknown",
    "--target-dir",
    "target",
    "--all-targets",
    "--",
    "-D",
    "warnings",
  ]);
  assert.deepEqual(command.env, {});
});

test("wasm-bindgen emits web glue without the name section", () => {
  assert.deepEqual(wasmBindgenArgs(VARIANTS.single), [
    "--target",
    "web",
    "--remove-name-section",
    "--out-dir",
    path.join("wasm", "single"),
    "--out-name",
    "primeval",
    VARIANTS.single.wasm,
  ]);
});

// --- Pins and wiring ---

test("subcommands print the nightly pin and the locked wasm-bindgen version", () => {
  const run = (command) =>
    spawnSync(process.execPath, ["scripts/build-wasm.mjs", command], { encoding: "utf8" });

  assert.equal(run("nightly").stdout, `${NIGHTLY_TOOLCHAIN}\n`);
  assert.equal(
    run("wasm-bindgen-version").stdout,
    `${lockedVersion(readRepoFile("Cargo.lock"), "wasm-bindgen")}\n`,
  );
  assert.match(NIGHTLY_TOOLCHAIN, /^nightly-\d{4}-\d{2}-\d{2}$/);
});

test("the nightly and wasm-bindgen-cli pins have one source", () => {
  const sources = [
    "package.json",
    "AGENTS.md",
    "CONTRIBUTING.md",
    "RELEASING.md",
    ...fs
      .readdirSync(path.join(repoRoot, ".github", "workflows"))
      .map((file) => path.join(".github", "workflows", file)),
  ];
  for (const file of sources) {
    const source = readRepoFile(file);
    assert.doesNotMatch(source, /nightly-\d{4}-\d{2}-\d{2}/, `${file} repeats the nightly pin`);
    assert.doesNotMatch(
      source,
      /wasm-bindgen-cli[^\n]*\d+\.\d+\.\d+/,
      `${file} repeats the wasm-bindgen-cli version`,
    );
  }

  const quality = readRepoFile(".github", "workflows", "quality.yml");
  assert.match(quality, /node scripts\/build-wasm\.mjs install-nightly/);
  assert.match(
    quality,
    /cargo install wasm-bindgen-cli --locked --version "\$\(node scripts\/build-wasm\.mjs wasm-bindgen-version\)"/,
  );
  assert.match(quality, /npm run verify:wasm/);
});

test("the pinned stable toolchain has the wasm target", () => {
  assert.match(readRepoFile("rust-toolchain.toml"), /^targets = \["wasm32-unknown-unknown"\]$/m);
});

test("verify runs the wasm checks", () => {
  const { scripts } = JSON.parse(readRepoFile("package.json"));

  assert.equal(scripts["build:wasm"], "node scripts/build-wasm.mjs");
  assert.equal(
    scripts["verify:wasm"],
    "node scripts/build-wasm.mjs clippy && npm run build:wasm && npm run build && npm run build:node && npm run test:browser",
  );
  assert.equal(scripts["test:browser"], "node --test test/browser/*.test.js");
  assert.match(scripts.verify, /npm run verify:wasm/);
});

test("the browser tests use a pinned Playwright and its Chromium headless shell in CI", () => {
  const { devDependencies } = JSON.parse(readRepoFile("package.json"));
  assert.match(
    devDependencies.playwright,
    /^\d+\.\d+\.\d+$/,
    "playwright must be an exact version",
  );

  const quality = readRepoFile(".github", "workflows", "quality.yml");
  const wasmJob = quality.slice(quality.indexOf("  wasm-checks:"), quality.indexOf("  hygiene:"));
  assert.match(wasmJob, /- run: npm ci\n/);
  // The locally installed (lockfile) Playwright picks the browser version.
  assert.match(wasmJob, /- run: npx playwright install --with-deps --only-shell chromium\n/);
  assert.ok(
    wasmJob.indexOf("npm ci") < wasmJob.indexOf("npx playwright install") &&
      wasmJob.indexOf("npx playwright install") < wasmJob.indexOf("npm run verify:wasm"),
    "wasm-checks must install dependencies, then the browser, then verify",
  );
});
