import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";

import {
  bumpPackageVersion,
  readCargoWorkspace,
  readCargoWorkspaceVersion,
  updateCargoWorkspaceVersion,
  validateCargoVersions,
} from "../../scripts/napi-targets.mjs";

const repoRoot = process.cwd();

const CARGO_TOML = `[workspace]
resolver = "3"
members = [
    "crates/a",
    "binding",
]

[workspace.package]
version = "0.1.1"
license = "MIT"

[profile.release]
lto = "fat"
`;

const MEMBER = (name) => `[package]
name = "${name}"
version.workspace = true
edition = "2024"

[dependencies]
serde = { version = "1" }
`;

const CARGO_LOCK = (versionA, versionB) => `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "a"
version = "${versionA}"

[[package]]
name = "b-node"
version = "${versionB}"
dependencies = [
 "a",
]

[[package]]
name = "serde"
version = "1.0.0"
`;

function workspace(overrides = {}) {
  return {
    cargoToml: CARGO_TOML,
    members: { "crates/a": MEMBER("a"), binding: MEMBER("b-node") },
    cargoLock: CARGO_LOCK("0.1.1", "0.1.1"),
    ...overrides,
  };
}

test("cargo workspace version is read from [workspace.package]", () => {
  assert.equal(readCargoWorkspaceVersion(CARGO_TOML), "0.1.1");
  assert.throws(() => readCargoWorkspaceVersion("[workspace]\n"), /workspace\.package/);
});

test("cargo workspace version update rewrites only [workspace.package] version", () => {
  const updated = updateCargoWorkspaceVersion(CARGO_TOML, "0.2.0-rc.1");
  assert.equal(readCargoWorkspaceVersion(updated), "0.2.0-rc.1");
  assert.equal(updated, CARGO_TOML.replace('version = "0.1.1"', 'version = "0.2.0-rc.1"'));
});

test("cargo versions validate when every crate inherits the npm version", () => {
  assert.doesNotThrow(() => validateCargoVersions("0.1.1", workspace()));
});

test("cargo versions reject a workspace version that drifts from npm", () => {
  assert.throws(
    () => validateCargoVersions("0.1.2", workspace()),
    /Cargo\.toml workspace version 0\.1\.1 must match package\.json version 0\.1\.2/,
  );
});

test("cargo versions reject a crate that does not inherit the workspace version", () => {
  const members = {
    "crates/a": MEMBER("a").replace("version.workspace = true", 'version = "0.1.1"'),
    binding: MEMBER("b-node"),
  };
  assert.throws(
    () => validateCargoVersions("0.1.1", workspace({ members })),
    /crates\/a\/Cargo\.toml must set version\.workspace = true/,
  );
});

test("cargo versions reject a stale Cargo.lock", () => {
  assert.throws(
    () => validateCargoVersions("0.1.1", workspace({ cargoLock: CARGO_LOCK("0.1.1", "0.1.0") })),
    /Cargo\.lock entry b-node is 0\.1\.0, expected 0\.1\.1/,
  );
});

test("repository cargo crate versions match the npm package version", () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(repoRoot, "package.json"), "utf8"));
  const cargo = readCargoWorkspace(repoRoot);
  assert.deepEqual(Object.keys(cargo.members).sort(), [
    "binding",
    "crates/primeval-core",
    "crates/primeval-render",
  ]);
  assert.doesNotThrow(() => validateCargoVersions(pkg.version, cargo));
});

const PACKAGE_NAME = "@aleburato/primeval";
const PLATFORM_PACKAGE = `${PACKAGE_NAME}-linux-x64-gnu`;

function writeFixtureProject(version) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "primeval-versions-"));
  const pkg = {
    name: PACKAGE_NAME,
    version,
    optionalDependencies: { [PLATFORM_PACKAGE]: version },
    napi: { binaryName: "primeval-node", targets: ["x86_64-unknown-linux-gnu"] },
  };
  fs.writeFileSync(path.join(dir, "package.json"), `${JSON.stringify(pkg, null, 2)}\n`);
  writePackageLock(dir, version);
  fs.writeFileSync(path.join(dir, "Cargo.toml"), CARGO_TOML.replace("0.1.1", version));
  for (const [member, name] of [
    ["crates/a", "a"],
    ["binding", "b-node"],
  ]) {
    fs.mkdirSync(path.join(dir, member), { recursive: true });
    fs.writeFileSync(path.join(dir, member, "Cargo.toml"), MEMBER(name));
  }
  fs.writeFileSync(path.join(dir, "Cargo.lock"), CARGO_LOCK(version, version));
  return dir;
}

function writePackageLock(dir, version) {
  const lock = {
    name: PACKAGE_NAME,
    version,
    lockfileVersion: 3,
    packages: {
      "": { name: PACKAGE_NAME, version, optionalDependencies: { [PLATFORM_PACKAGE]: version } },
      [`node_modules/${PLATFORM_PACKAGE}`]: { version },
    },
  };
  fs.writeFileSync(path.join(dir, "package-lock.json"), `${JSON.stringify(lock, null, 2)}\n`);
}

// Stands in for `npm install --package-lock-only` and `cargo update --workspace`.
function fakeTools(dir, { failCargo = false } = {}) {
  const calls = [];
  const run = (command, args) => {
    calls.push([path.basename(command).replace(/\.cmd$/, ""), ...args]);
    const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
    if (command.startsWith("npm")) {
      writePackageLock(dir, pkg.version);
    } else if (failCargo) {
      throw new Error("cargo failed");
    } else {
      const cargoVersion = readCargoWorkspaceVersion(
        fs.readFileSync(path.join(dir, "Cargo.toml"), "utf8"),
      );
      fs.writeFileSync(path.join(dir, "Cargo.lock"), CARGO_LOCK(cargoVersion, cargoVersion));
    }
  };
  return { calls, run };
}

test("bump-version also bumps the cargo workspace version and Cargo.lock", () => {
  const dir = writeFixtureProject("0.1.1");
  try {
    const tools = fakeTools(dir);
    bumpPackageVersion(
      "0.2.0",
      path.join(dir, "package.json"),
      path.join(dir, "package-lock.json"),
      tools,
    );

    assert.deepEqual(tools.calls, [
      ["npm", "install", "--package-lock-only", "--ignore-scripts"],
      ["cargo", "update", "--workspace", "--offline"],
    ]);
    assert.equal(
      readCargoWorkspaceVersion(fs.readFileSync(path.join(dir, "Cargo.toml"), "utf8")),
      "0.2.0",
    );
    assert.doesNotThrow(() => validateCargoVersions("0.2.0", readCargoWorkspace(dir)));
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("bump-version restores every file when the cargo step fails", () => {
  const dir = writeFixtureProject("0.1.1");
  const files = ["package.json", "package-lock.json", "Cargo.toml", "Cargo.lock"];
  const before = files.map((file) => fs.readFileSync(path.join(dir, file), "utf8"));
  try {
    assert.throws(
      () =>
        bumpPackageVersion(
          "0.2.0",
          path.join(dir, "package.json"),
          path.join(dir, "package-lock.json"),
          fakeTools(dir, { failCargo: true }),
        ),
      /cargo failed/,
    );
    assert.deepEqual(
      files.map((file) => fs.readFileSync(path.join(dir, file), "utf8")),
      before,
    );
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("check-package fails when the cargo versions drift from package.json", () => {
  const dir = writeFixtureProject("0.1.1");
  try {
    const ok = spawnSync(
      process.execPath,
      ["scripts/napi-targets.mjs", "check-package", path.join(dir, "package.json")],
      { cwd: repoRoot, encoding: "utf8" },
    );
    assert.equal(ok.status, 0, ok.stderr);

    fs.writeFileSync(path.join(dir, "Cargo.lock"), CARGO_LOCK("0.1.1", "0.1.0"));
    const drift = spawnSync(
      process.execPath,
      ["scripts/napi-targets.mjs", "check-package", path.join(dir, "package.json")],
      { cwd: repoRoot, encoding: "utf8" },
    );
    assert.equal(drift.status, 1);
    assert.match(drift.stderr, /Cargo\.lock entry b-node is 0\.1\.0, expected 0\.1\.1/);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});
