[package]
name = "primeval-core"
version = "0.1.0"
edition = "2024"
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
rand = { version = "0.10", default-features = false }
rand_chacha = "0.10"
rand_distr = "0.6"
rayon = "1.10"

[dev-dependencies]
approx = "0.5"
