import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  readPackageMetadata,
  requiredString,
  runtimeTargetForTarget,
  validatePackageMetadata,
} from "./napi-targets.mjs";

const SCRIPTS_DIR = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_PACKAGE_JSON = path.resolve(SCRIPTS_DIR, "..", "package.json");
const DEFAULT_OUTPUT = path.resolve(SCRIPTS_DIR, "..", "binding.js");

export function bindingMetadataForPackage(pkg) {
  const { packageName, targets } = validatePackageMetadata(pkg);
  const binaryName = requiredString(pkg.napi?.binaryName, "package.json napi.binaryName");

  return {
    targets: targets.map((target) => {
      const runtime = runtimeTargetForTarget(target);
      return {
        ...runtime,
        packageName: `${packageName}-${runtime.suffix}`,
        localFile: `./${binaryName}.${runtime.suffix}.node`,
      };
    }),
  };
}

function renderTargetMetadata(targets) {
  return targets
    .map(
      (target) => `  {
    platform: '${target.platform}',
    arch: '${target.arch}',
    abi: ${target.abi === null ? "null" : `'${target.abi}'`},
    packageName: '${target.packageName}',
    localFile: '${target.localFile}'
  }`,
    )
    .join(",\n");
}

function renderSwitchCases(targets, key) {
  return targets
    .map(
      (target) => `    case '${target[key]}':
      return require('${target[key]}')`,
    )
    .join("\n");
}

export function renderBindingLoader(pkg) {
  const { targets } = bindingMetadataForPackage(pkg);

  return `// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by scripts/generate-binding.mjs */

import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)

const TARGETS = [
${renderTargetMetadata(targets)}
]

function detectLinuxLibc() {
  if (process.platform !== 'linux') {
    return null
  }

  const report = typeof process.report?.getReport === 'function'
    ? process.report.getReport()
    : null
  const header = report?.header
  if (
    header &&
    typeof header.glibcVersionRuntime === 'string' &&
    header.glibcVersionRuntime.length > 0
  ) {
    return 'gnu'
  }

  const sharedObjects = report?.sharedObjects
  if (
    Array.isArray(sharedObjects) &&
    sharedObjects.some(
      (entry) =>
        typeof entry === 'string' &&
        (entry.includes('ld-musl-') || entry.includes('libc.musl-')),
    )
  ) {
    return 'musl'
  }

  return null
}

function currentRuntimeAbi() {
  if (process.platform !== 'linux') {
    return null
  }

  return detectLinuxLibc()
}

function supportedTargetsForCurrentPlatform() {
  return TARGETS.filter(
    (t) => t.platform === process.platform && t.arch === process.arch,
  )
}

function formatTarget(target) {
  return target.abi === null
    ? target.platform + '-' + target.arch
    : target.platform + '-' + target.arch + '-' + target.abi
}

// Match the current platform, architecture, and Linux ABI against declared targets.
function findTarget() {
  const runtimeAbi = currentRuntimeAbi()
  return TARGETS.find(
    (t) =>
      t.platform === process.platform &&
      t.arch === process.arch &&
      (t.abi === null || t.abi === runtimeAbi),
  ) ?? null
}

function unsupportedRuntimeError() {
  const platformTargets = supportedTargetsForCurrentPlatform()
  if (platformTargets.length === 0) {
    const supported = TARGETS.map(formatTarget).join(', ')
    return new Error(
      'Unsupported OS: ' +
        process.platform +
        ', architecture: ' +
        process.arch +
        '. This package ships prebuilds only for ' +
        supported +
        '.',
    )
  }

  if (process.platform === 'linux') {
    const runtimeAbi = currentRuntimeAbi()
    const supportedAbis = [
      ...new Set(
        platformTargets
          .map((target) => target.abi)
          .filter((abi) => typeof abi === 'string'),
      ),
    ]

    if (runtimeAbi === 'musl' && !supportedAbis.includes('musl')) {
      return new Error(
        'Unsupported Linux runtime: linux-' +
          process.arch +
          '-musl. Published native addons currently support GNU libc only for this architecture (' +
          supportedAbis.join(', ') +
          '). Alpine/musl is not supported yet.',
      )
    }

    if (runtimeAbi === null) {
      return new Error(
        'Unsupported Linux runtime: unable to detect libc for linux-' +
          process.arch +
          '. Published native addons for this architecture require one of: ' +
          supportedAbis.join(', ') +
          '.',
      )
    }

    return new Error(
      'Unsupported Linux runtime: linux-' +
        process.arch +
        '-' +
        runtimeAbi +
        '. Published native addons for this architecture require one of: ' +
        supportedAbis.join(', ') +
        '.',
    )
  }

  const supported = platformTargets.map(formatTarget).join(', ')
  return new Error(
    'Unsupported runtime: ' +
      process.platform +
      '-' +
      process.arch +
      '. Published native addons for this platform/architecture are: ' +
      supported +
      '.',
  )
}

function describeLoadError(error) {
  if (error instanceof Error) {
    return error.message
  }

  return String(error)
}

function requireLocalFile(localFile) {
  switch (localFile) {
${renderSwitchCases(targets, "localFile")}
    default:
      throw new Error(\`Unsupported local binding file: \${localFile}\`)
  }
}

function requireOptionalPackage(packageName) {
  switch (packageName) {
${renderSwitchCases(targets, "packageName")}
    default:
      throw new Error(\`Unsupported native package: \${packageName}\`)
  }
}

function loadNativeBinding() {
  const target = findTarget()
  if (!target) {
    throw unsupportedRuntimeError()
  }

  let localError
  try {
    return requireLocalFile(target.localFile)
  } catch (error) {
    localError = error
  }

  try {
    return requireOptionalPackage(target.packageName)
  } catch (packageError) {
    const combined = new Error(
      [
        \`Failed to load native binding for \${target.localFile}.\`,
        \`Tried local file \${target.localFile} and package \${target.packageName}.\`,
        'Make sure optional dependencies were installed (do not use --omit=optional or equivalent settings) and that you are running Node 22.12+ on a supported platform.',
        \`Local file error: \${describeLoadError(localError)}\`,
        \`Package error: \${describeLoadError(packageError)}\`,
      ].join(' '),
    )
    combined.cause = packageError
    throw combined
  }
}

export const { NativeTask, startApproximate } = loadNativeBinding()
`;
}

export function writeBindingLoader(
  packageJsonPath = DEFAULT_PACKAGE_JSON,
  outputPath = DEFAULT_OUTPUT,
) {
  const pkg = readPackageMetadata(packageJsonPath);
  const source = renderBindingLoader(pkg);
  fs.writeFileSync(outputPath, source);
  return outputPath;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const packageJsonPath = process.argv[2] ? path.resolve(process.argv[2]) : DEFAULT_PACKAGE_JSON;
  const outputPath = process.argv[3] ? path.resolve(process.argv[3]) : DEFAULT_OUTPUT;
  writeBindingLoader(packageJsonPath, outputPath);
  console.log(path.relative(process.cwd(), outputPath));
}
